import { newFillId, newTradeId, type Fill, type Trade } from '../types'


function fill(
  kind: Fill['kind'],
  date: string,
  price: number,
  quantity: number,
  fees = 0,
  note = '',
  createdAt = Date.parse(`${date}T15:00:00Z`),
): Fill {
  return { id: newFillId(), kind, date, price, quantity, fees, note, createdAt }
}

function t(
  partial: Omit<Trade, 'id' | 'createdAt' | 'updatedAt' | 'fills'> & { fills?: Fill[]; createdAt?: number },
): Trade {
  const createdAt = partial.createdAt ?? Date.parse(`${partial.entryDate}T15:00:00Z`)
  return {
    fills: [],
    ...partial,
    id: newTradeId(),
    createdAt,
    updatedAt: createdAt + 86_400_000,
  }
}

export function demoTrades(): Trade[] {
  return [
    t({
      symbol: 'AAPL',
      side: 'long',
      quantity: 40,
      entryPrice: 178.4,
      entryDate: '2026-01-14',
      exitPrice: 186.25,
      exitDate: '2026-01-22',
      fees: 1.99,
      stopLoss: 174.1,
      takeProfit: 188,
      setup: 'Pullback',
      tags: ['tech', 'large-cap'],
      grade: 'A',
      thesis: 'Held the 50-day after a clean earnings dip. Risk defined under the swing low.',
      emotion: 'Calm. Waited for the higher low instead of chasing the first green day.',
      mistakes: '',
      lessons: 'Let the planned target work. Partial at +1R would have been optional, not required.',
    }),
    t({
      symbol: 'NVDA',
      side: 'long',
      quantity: 12,
      entryPrice: 132.8,
      entryDate: '2026-01-28',
      exitPrice: 128.15,
      exitDate: '2026-01-29',
      fees: 1.99,
      stopLoss: 128.2,
      takeProfit: 142,
      setup: 'Breakout',
      tags: ['semis', 'momentum'],
      grade: 'B',
      thesis: 'Range break on volume. Size was fine; the follow-through never showed.',
      emotion: 'Slight FOMO after two green opens. Still honored the stop.',
      mistakes: 'Entered late in the day instead of on the opening drive confirmation.',
      lessons: 'A valid stop-out is an A execution even when the idea is wrong.',
    }),
    t({
      symbol: 'SPY',
      side: 'short',
      quantity: 20,
      entryPrice: 598.6,
      entryDate: '2026-02-06',
      exitPrice: 591.2,
      exitDate: '2026-02-11',
      fees: 2.5,
      stopLoss: 602.4,
      takeProfit: 588,
      setup: 'Reversal',
      tags: ['index', 'mean-reversion'],
      grade: 'A+',
      thesis: 'Failed breakout into a prior weekly high with weakening internals.',
      emotion: 'Patient. Scaled risk down because it was a countertrend idea.',
      mistakes: '',
      lessons: 'Shorts work best when the failed break is obvious on the daily.',
    }),
    t({
      symbol: 'TSLA',
      side: 'long',
      quantity: 25,
      entryPrice: 248.9,
      entryDate: '2026-02-18',
      exitPrice: 236.4,
      exitDate: '2026-02-20',
      fees: 1.99,
      stopLoss: 241.5,
      takeProfit: 265,
      setup: 'Momentum',
      tags: ['volatile'],
      grade: 'C',
      thesis: 'News spike. Wanted continuation into the round number.',
      emotion: 'Rushed. Sized too large for the ATR.',
      mistakes: 'Stop was inside normal noise. Moved it once, then got tagged.',
      lessons: 'If the stop has to live inside the noise, the size is wrong.',
    }),
    t({
      symbol: 'MSFT',
      side: 'long',
      quantity: 18,
      entryPrice: 412.15,
      entryDate: '2026-03-04',
      exitPrice: 424.8,
      exitDate: '2026-03-13',
      fees: 1.99,
      stopLoss: 405,
      takeProfit: 430,
      setup: 'Pullback',
      tags: ['tech', 'quality'],
      grade: 'A',
      thesis: 'Flag under prior high. Breadth in software was constructive.',
      emotion: 'Steady. Journaled the plan the night before.',
      mistakes: '',
      lessons: 'Overnight planning removes most of the morning noise.',
    }),
    t({
      symbol: 'AMD',
      side: 'long',
      quantity: 30,
      entryPrice: 168.2,
      entryDate: '2026-03-19',
      exitPrice: 175.6,
      exitDate: '2026-03-24',
      fees: 1.99,
      stopLoss: 163.4,
      takeProfit: 178,
      setup: 'Breakout',
      tags: ['semis'],
      grade: 'B',
      thesis: 'Relative strength vs NVDA during a sector pause.',
      emotion: 'Confident but not attached.',
      mistakes: 'Took profits a little early into the first stall.',
      lessons: 'Trail with structure, not a round number, when RS is that clean.',
    }),
    t({
      symbol: 'COIN',
      side: 'long',
      quantity: 15,
      entryPrice: 212.4,
      entryDate: '2026-04-02',
      exitPrice: 198.75,
      exitDate: '2026-04-03',
      fees: 1.99,
      stopLoss: 204,
      takeProfit: 230,
      setup: 'News',
      tags: ['crypto-beta'],
      grade: 'D',
      thesis: 'Headline bid. No level, just a story.',
      emotion: 'Excited. That is usually a warning.',
      mistakes: 'Traded the headline instead of a level. No real edge.',
      lessons: 'If I cannot point to a level, I do not click.',
    }),
    t({
      symbol: 'META',
      side: 'long',
      quantity: 14,
      entryPrice: 548.3,
      entryDate: '2026-04-16',
      exitPrice: 571.1,
      exitDate: '2026-04-28',
      fees: 1.99,
      stopLoss: 536,
      takeProfit: 575,
      setup: 'Earnings',
      tags: ['tech', 'event'],
      grade: 'A',
      thesis: 'Held value area after the print. Risk under the earnings gap low.',
      emotion: 'Slightly anxious overnight, size was half-normal.',
      mistakes: '',
      lessons: 'Halving size into events keeps the grade high even when the move is large.',
    }),
    t({
      symbol: 'AMZN',
      side: 'short',
      quantity: 16,
      entryPrice: 189.7,
      entryDate: '2026-05-07',
      exitPrice: 192.85,
      exitDate: '2026-05-08',
      fees: 1.99,
      stopLoss: 192.9,
      takeProfit: 182,
      setup: 'Mean reversion',
      tags: ['retail'],
      grade: 'B',
      thesis: 'Stretch above VWAP into resistance. Fade with a tight stop.',
      emotion: 'Neutral.',
      mistakes: 'Right idea, market just kept grinding. Stop did its job.',
      lessons: 'Mean reversion needs failed acceptance, not only an extended print.',
    }),
    t({
      symbol: 'PLTR',
      side: 'long',
      quantity: 50,
      entryPrice: 74.15,
      entryDate: '2026-05-20',
      exitPrice: 81.4,
      exitDate: '2026-06-03',
      fees: 1.99,
      stopLoss: 70.8,
      takeProfit: 82,
      setup: 'Momentum',
      tags: ['high-beta'],
      grade: 'A+',
      thesis: 'Trend continuation after a tight bull flag. Volume confirmed.',
      emotion: 'Patient. Added only after the first higher low.',
      mistakes: '',
      lessons: 'The best trades feel almost boring after the plan is written.',
    }),
    t({
      symbol: 'AVGO',
      side: 'long',
      quantity: 10,
      entryPrice: 1284,
      entryDate: '2026-06-11',
      exitPrice: 1312.5,
      exitDate: '2026-06-18',
      fees: 2.5,
      stopLoss: 1255,
      takeProfit: 1340,
      setup: 'Pullback',
      tags: ['semis', 'quality'],
      grade: 'B',
      thesis: 'Higher-low into the 20-day. Semis still leading.',
      emotion: 'Fine.',
      mistakes: 'Could have given it more room; still a solid R.',
      lessons: 'Expensive names need fewer shares, not wider stops.',
    }),
    t({
      symbol: 'QQQ',
      side: 'long',
      quantity: 15,
      entryPrice: 512.3,
      entryDate: '2026-06-26',
      exitPrice: 508.1,
      exitDate: '2026-06-27',
      fees: 1.99,
      stopLoss: 508,
      takeProfit: 522,
      setup: 'Gap fill',
      tags: ['index'],
      grade: 'C',
      thesis: 'Gap fill long after a risk-off open that reversed.',
      emotion: 'Impatient. Entered before the reclaim was real.',
      mistakes: 'Anticipated the reclaim instead of waiting for it.',
      lessons: 'Index scalps need confirmation. No extra credit for being early.',
    }),
    t({
      symbol: 'NFLX',
      side: 'long',
      quantity: 8,
      entryPrice: 978.5,
      entryDate: '2026-07-09',
      exitPrice: 1006.2,
      exitDate: '2026-07-17',
      fees: 1.99,
      stopLoss: 958,
      takeProfit: 1020,
      setup: 'Breakout',
      tags: ['media'],
      grade: 'A',
      thesis: 'Multi-week coil. Broke out with the sector, held the opening range.',
      emotion: 'Calm.',
      mistakes: '',
      lessons: 'Coils that last weeks often pay for the wait in a few sessions.',
    }),
    t({
      symbol: 'COST',
      side: 'long',
      quantity: 6,
      entryPrice: 942.1,
      entryDate: '2026-07-28',
      exitPrice: 931.4,
      exitDate: '2026-07-30',
      fees: 1.99,
      stopLoss: 931.2,
      takeProfit: 970,
      setup: 'Earnings',
      tags: ['consumer', 'event'],
      grade: 'B',
      thesis: 'Defensive earnings hold. Stop under the gap.',
      emotion: 'Slightly hesitant — mixed tape.',
      mistakes: 'The tape was not confirming defensive rotation.',
      lessons: 'Event trades still need a market regime that matches the story.',
    }),
    t({
      symbol: 'NVDA',
      side: 'long',
      quantity: 25,
      entryPrice: 140.24,
      entryDate: '2026-08-06',
      exitPrice: null,
      exitDate: null,
      fees: 1.99,
      stopLoss: 136.4,
      takeProfit: 155,
      setup: 'Pullback',
      tags: ['semis', 'open'],
      grade: null,
      thesis: 'Reset to the rising 21-day. Added on the next higher low.',
      emotion: 'Constructive. Size is 0.8R of usual.',
      mistakes: '',
      lessons: '',
      fills: [
        fill('add', '2026-08-06', 141.6, 15, 0, 'First lot'),
        fill('add', '2026-08-11', 138.2, 10, 1.99, 'Added on the higher low'),
      ],
    }),
    t({
      symbol: 'AAPL',
      side: 'long',
      quantity: 20,
      entryPrice: 214.75,
      entryDate: '2026-08-12',
      exitPrice: null,
      exitDate: null,
      fees: 1.99,
      stopLoss: 209.5,
      takeProfit: 226,
      setup: 'Momentum',
      tags: ['tech', 'open'],
      grade: null,
      thesis: 'Break and hold of the prior month high. Took a third off into strength.',
      emotion: 'Neutral-positive.',
      mistakes: '',
      lessons: '',
      fills: [
        fill('add', '2026-08-12', 214.75, 30, 0, 'Opening lot'),
        fill('trim', '2026-08-17', 219.4, 10, 1.99, 'Took a third off'),
      ],
    }),
  ]
}
